### ISSUE TITLE
I cannot get correct the results

### ISSUE THREAD

**Issue by huq02** [Kazuhito00/hand-gesture-recognition-using-mediapipe#11]
1. I have finish the training based on the point_history.csv， but I cannot get the correct the results compare with weights you provided， I don‘t known why？
2. I collect the training data about Stop、Clockwise、Anti_Clockwise、Moving、Click、grab，but  I also can't get correct the results，just only ’stop‘。

**Comment by Kazuhito00** [comment]
The models provided in this repository are models trained on the included dataset.
I don't know unless you describe the detailed conditions you tried.

**Comment by huq02** [comment]
When two hands or more ，why the status of two hand are only the moving。











At 2022-08-13 20:08:35, "胡强" ***@***.***> wrote:

I  have finish the training based on the dataset.csv you provided.  I test by camera ，the results only the stop。

I want to get the click and grab moving gesture ，can you give me some skills?



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/13/2022 20:03 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [Kazuhito00/hand-gesture-recognition-using-mediapipe] I cannot get correct the results (Issue #11) |

The models provided in this repository are models trained on the included dataset.
I don't know unless you describe the detailed conditions you tried.

**Comment by Kazuhito00** [comment]
This repository is for one hand.

**Comment by Kazuhito00** [comment]
It will close because time has passed.
If you have another problem, please create the issue again.

**Comment by huq02** [comment]
I  have finish the training based on the dataset.csv you provided.  I test by camera ，the results only the stop。

I want to get the click and grab moving gesture ，can you give me some skills?



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/13/2022 20:03 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [Kazuhito00/hand-gesture-recognition-using-mediapipe] I cannot get correct the results (Issue #11) |

The models provided in this repository are models trained on the included dataset.
I don't know unless you describe the detailed conditions you tried.

**Comment by adarmawan117** [comment]
> This repository is for one hand.

Hi, Kazuhito00.
How to change this repo to detect two hands.?
