### ISSUE TITLE
more than 9 gestures.

### ISSUE THREAD

**Issue by calderonjefry1713** [Kazuhito00/hand-gesture-recognition-using-mediapipe#16]
Hello friend, I have been experimenting with your project to enter a raspberry and try it in the translation but I want to enter more than 9 gestures, I don't know if you can support me, it is from your next project.

**Comment by calderonjefry1713** [comment]
I already integrated it into the raspberry 4 and I was able to make it portable but I can't make it add more than 9 gestures.

**Comment by jefrycalde** [comment]
![imagen_2023-08-22_173244311](https://github.com/Kazuhito00/hand-gesture-recognition-using-mediapipe/assets/84283354/4871128a-e391-41d4-9783-a9b649f32c47)
I manage to make it add more 10 but it tells me index error list

**Comment by Kazuhito00** [comment]
There are no plans to support this in this repository, but it can be achieved by changing select_mode() and logging_csv().
