### ISSUE TITLE
model.fit

### ISSUE THREAD

**Issue by FKQ7** [Kazuhito00/hand-gesture-recognition-using-mediapipe#17]
Jupyter notebook. I have an error in "model.fit(
    X_train,
    y_train,
    epochs=1000,
    batch_size=128,
    validation_data=(X_test, y_test),
    callbacks=[cp_callback, es_callback]
)"
It said "InvalidArgumentError                      Traceback (most recent call last)
Cell In[32], line 1"
I don't understand why and how to fix this problem, can you help me with this error?
Thank you very much!

**Comment by Kazuhito00** [comment]
I'm missing information for me to identify the problem.
Have you changed your notebook or dataset?
Also, what are the versions of each package at runtime?

**Comment by FKQ7** [comment]
yes, i have change the dataset, 
versions of the packages are as same as the requirements.txt but i get a problem with TensorFlow so i updated it to the last update because of my Cuda version.

**Comment by FKQ7** [comment]
yes i have change the dataset, 
versions of the packages are as same as the requirements.txt but i get a problem with TensorFlow so i updated it to the last update because of my Cuda version.

**Comment by Kazuhito00** [comment]
We don't have enough information yet.
What is the specific version of the updated package?
Also, is it possible to share modified datasets for problem analysis?

**Comment by Kazuhito00** [comment]
I'm closing this post because I haven't had a reply for a while.
When filing an issue again, please complete the information.
