### ISSUE TITLE
Undefined gestures give false positives.

### ISSUE THREAD

**Issue by kkzh2313** [Kazuhito00/hand-gesture-recognition-using-mediapipe#2]
If there is no defined gesture it will also be forced to assign a gesture category, how to solve this problem?

**Comment by Kazuhito00** [comment]
What does "If there is no defined gesture" mean?

・Performed gestures not found in the learning class?
・Performed a gesture not included in the following label definition?
　keypoint_classifier_label.csv
　point_history_classifier_label.csv
・Other

**Comment by kkzh2313** [comment]
@Kazuhito00 Yes, the second meaning. For a new gesture, the classifier also assigns a category from the CSV file and the score may be very high.

**Comment by Kazuhito00** [comment]
If you used a pre-trained model, the inference results would inevitably fall into one of the classes.
If you want to avoid this situation, you have several ways

* Collect learning data for undefined gestures, add new classes and retrain the model
* Change the model structure and use Metric Learning to make a judgment based on the threshold value.

If you want to retrain, please check the README.md for the procedure.
The Metric Learning method is not supported in this repository.

**Comment by Kazuhito00** [comment]
It will close because time has passed.
If you have another problem, please create the issue again.
