### ISSUE TITLE
train dataset of PointHistoryClassifier?

### ISSUE THREAD

**Issue by brooks0519** [Kazuhito00/hand-gesture-recognition-using-mediapipe#3]
Hi Kazuhito00, thank you very much for you cool job. I have a question about the train dataset of the point_history_classifier. I   want to extend your demo with my own gesture, but when I collect my own train dataset and train the new model, I find the new 
 model can't recognise the new gesture correctly. I collect my data like this, After I Press 'h' and enter the mode to save the history of fingertip coordinates, I press '4' while completing the gesture and save the figure coordinate to the csv for train new model. Total num of the added data is about 500. Can you help me point out the problem？TKS！

**Comment by Kazuhito00** [comment]
Please check and tell me some things to solve the problem.

* Did you change the NUM_CLASSES in "point_history_classification.ipynb"?
* Did you add a new class label to "point_history_classifier_label.csv"?
* Check the confusion matrix and find a lot of wrong result?

If all of the above are okay, share your train data and notebook.

**Comment by chiminghui** [comment]
Thank you for your replay. firstly,I have change the NUM_CLASSES to four(for I add a new gesture);

**Comment by brooks0519** [comment]
Thank you for your replay.
firstly, I have change the NUM_CLASSES in "point_history_classification.ipynb" to 5(as I add a new gesture);
secondly, I have add a new class label to "point_history_classifier_label.csv" which index is 4;
thirdly, the matrix is as bellow: 
![image](https://user-images.githubusercontent.com/16219166/123587873-801b8000-d819-11eb-8ee4-3f3d25af773b.png)

and the train data and notebook is here:
[point_history_classification.zip](https://github.com/Kazuhito00/hand-gesture-recognition-using-mediapipe/files/6723821/point_history_classification.zip)

my new gesture is like this in the below pic:
![image](https://user-images.githubusercontent.com/16219166/123588347-32ebde00-d81a-11eb-9bab-9d577bf171b2.png)

**Comment by brooks0519** [comment]
I am so sorry to disturb you, I have find the reason of the prroblem. because after I train my dataset in the notebook, I didn't  run the part h5->tflite, so the inference model is also the original model you give. After I run the h5->tflite, the demo app.py can get the right result as expect.  Thanks again for your great job!

**Comment by Kazuhito00** [comment]
I'm glad I solved it.
