### ISSUE TITLE
How was the data generated?

### ISSUE THREAD

**Issue by HungDuong1998** [Kazuhito00/hand-gesture-recognition-using-mediapipe#4]
I want to train my new gesture. But I see your dataset has a whopping 5k rows with approx 1k each gesture.

Was your data genuinely taken from 5k press on the app or it was generated by some trick?

How can I give the model a good dataset?

Many thanks

**Comment by Kazuhito00** [comment]
I haven't done anything special in collecting data.
Data is collected by the following procedures.

https://github.com/Kazuhito00/hand-gesture-recognition-using-mediapipe/blob/main/README_EN.md#1learning-data-collection
https://github.com/Kazuhito00/hand-gesture-recognition-using-mediapipe/blob/main/README_EN.md#1learning-data-collection-1

Data is collected while the key is pressed, so after a while, more than 1k of data will be collected.

**Comment by HungDuong1998** [comment]
I want to understand more about the nature of data you collected and your model, why does it need ~1k data for 1 keypoint in the history part?

I collected myself some set of movement data but it's easier collecting the still data (hand stop) than the moving data. I modified your model a little bit to collect the history of 2 key points instead of 1 for more information feed into the model. Does it mean I need more data or need a more complex model.

Many thanks.

**Comment by Kazuhito00** [comment]
The number of 1000 data doesn't make much sense.
This is just an example.
Also, I don't think this is the best number of data or model structures.

If the recognition accuracy you require is not sufficient, consider adding data or changing the model structure.

**Comment by Kazuhito00** [comment]
It will close because time has passed.
If you have another problem, please create the issue again.
