### ISSUE TITLE
Slow FPS 4 to 5 on Ubuntu 18.04 with NVIDIA GeForce RTX 2080 Ti

### ISSUE THREAD

**Issue by malpeddinilesh** [Kazuhito00/hand-gesture-recognition-using-mediapipe#9]
Hi @Kazuhito00 ,

Thank you for your work on this. 

I was just trying and playing with the your repo and I have observed that FPS on my Ubuntu 18.04 with NVIDIA GeForce RTX 2080 Ti I am seeing only 4 to 5 FPS, whereas at your side I am seeing 25 to 30 FPS. 

I have tried using following:

1. TF lite model which was already in the repo - but same 4 to 5 FPS. 
2. Build and compile TF lite model on using the HDF5 model in the repo. Converted HDF5 model from repo to TF lite model on my machine, but same 4 to 5 FPS.
3. Directly using HDF5 models for key point classifier and point history classifier model doing prediction / inference on GPU but still no luck same 4 to 5 FPS.

It will be helpful if you can provide some guidance on why at my side getting only 4 to 5 FPS.

**Comment by Kazuhito00** [comment]
The tflite model in this repository assumes CPU inference.
If you want to perform GPU inference, use the TensorFlow model without converting the model to tflite.
The source code of this repository is based on the tflite model, so if you use the TensorFlow model, please modify the source code yourself.

**Comment by Kazuhito00** [comment]
It will close because time has passed.
If you have another problem, please create the issue again.

**Comment by malpeddinilesh** [comment]
Thank you @Kazuhito00 for your response on this!
